#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

clipboard-receiver &
CLIPBOARD_PID=$!
trap "kill $CLIPBOARD_PID 2>/dev/null" EXIT

# See: https://gist.github.com/dergachev/8259104
ssh -R 5556:localhost:5556 "$@"
