---
- name: Ensure ~/.bashrc.d directory exists
  file:
    path: "/home/{{ workstation_user }}/.bashrc.d"
    state: directory
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: '0755'
  become: true
  become_user: root

- name: Ensure ~/.bashrc sources ~/.bashrc.d/
  blockinfile:
    path: "/home/{{ workstation_user }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: bashrc.d"
    block: |
      for f in ~/.bashrc.d/*.sh; do source "$f"; done
    create: true
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: '0644'
  become: true
  become_user: root

- name: Set SSH login starting directory to ansible-workstation-patcon
  copy:
    dest: "/home/{{ workstation_user }}/.bashrc.d/ssh-start-dir.sh"
    content: |
      if [[ -n "$SSH_CONNECTION" ]] && [[ $- == *i* ]]; then
        cd ~/repos/ansible-workstation-patcon
      fi
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: '0644'
  become: true
  become_user: root

- name: Configure git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ personalization_git_name }}"
  become: true
  become_user: "{{ workstation_user }}"

- name: Configure git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ personalization_git_email }}"
  become: true
  become_user: "{{ workstation_user }}"

